<?php

declare(strict_types=1);

return [
    'paper' => [
        'title' => 'Assessment and Hardening of IoT Development Boards',
        'authors' => ['Omar Alfandi', 'Musaab Hasan', 'Zayed Balbahaith'],
        'year' => 2019,
        'venue' => 'Wired/Wireless Internet Communications, WWIC 2019',
        'series' => 'Lecture Notes in Computer Science',
        'volume' => '11618',
        'pages' => '27-39',
        'publisher' => 'Springer, Cham',
        'doi' => '10.1007/978-3-030-30523-9_3',
        'doi_url' => 'https://doi.org/10.1007/978-3-030-30523-9_3',
        'springer_url' => 'https://link.springer.com/chapter/10.1007/978-3-030-30523-9_3',
        'repository_url' => 'https://zuscholars.zu.ac.ae/works/582/',
        'keywords' => [
            'IoT',
            'Raspberry Pi 3',
            'Man-in-the-middle attack',
            'Remote authentication',
            'SSH keys',
            'OpenSSH',
        ],
        'citation' => 'Alfandi, O., Hasan, M., & Balbahaith, Z. (2019). Assessment and Hardening of IoT Development Boards. In M. Di Felice, E. Natalizio, R. Bruno, & A. Kassler (Eds.), Wired/Wireless Internet Communications, WWIC 2019, Lecture Notes in Computer Science, vol. 11618, pp. 27-39. Springer, Cham. https://doi.org/10.1007/978-3-030-30523-9_3',
        'summary' => 'The paper evaluates SSH exposure on Raspberry Pi and comparable IoT development boards, demonstrates downgrade and man-in-the-middle risks when weak SSH configurations are present, and proposes hardening measures for protocol selection, key generation, entropy, and trusted key validation.',
    ],
    'threats' => [
        [
            'id' => 'ssh-v1-downgrade',
            'name' => 'SSH protocol downgrade',
            'severity' => 'Critical',
            'category' => 'Remote access',
            'paper_signal' => 'The paper shows that allowing SSH V1 and V2 together can enable downgrade behavior during a man-in-the-middle scenario.',
            'business_impact' => 'Administrative credentials can be exposed, creating a path to device takeover and lateral movement.',
            'recommended_controls' => ['ssh-protocol-2', 'ssh-config-audit', 'mitm-monitoring'],
        ],
        [
            'id' => 'weak-first-boot-keys',
            'name' => 'Weak first-boot SSH host keys',
            'severity' => 'Critical',
            'category' => 'Cryptographic assurance',
            'paper_signal' => 'The paper highlights predictable key generation risk when cloned operating-system images boot on similar board hardware with limited entropy.',
            'business_impact' => 'A device may appear encrypted while still being vulnerable to impersonation or session interception.',
            'recommended_controls' => ['regenerate-host-keys', 'hardware-rng', 'key-inventory'],
        ],
        [
            'id' => 'arp-mitm',
            'name' => 'ARP poisoning and local man-in-the-middle',
            'severity' => 'High',
            'category' => 'Network trust',
            'paper_signal' => 'The experiment uses ARP poisoning to place an intermediary host between the SSH client and the board.',
            'business_impact' => 'Local network attackers can observe, manipulate, or downgrade administrative sessions when controls are weak.',
            'recommended_controls' => ['mitm-monitoring', 'network-segmentation', 'admin-network'],
        ],
        [
            'id' => 'outdated-openssh',
            'name' => 'Outdated OpenSSH exposure',
            'severity' => 'High',
            'category' => 'Patch management',
            'paper_signal' => 'The paper reviews vulnerability categories affecting OpenSSH versions, including denial of service, bypass, information disclosure, and privilege gain.',
            'business_impact' => 'Unpatched SSH services increase the probability of exploit chaining after discovery.',
            'recommended_controls' => ['openssh-patching', 'version-baseline', 'vulnerability-tracking'],
        ],
        [
            'id' => 'default-image-attack-surface',
            'name' => 'Default image attack surface',
            'severity' => 'High',
            'category' => 'System minimization',
            'paper_signal' => 'The paper notes that newer board images may include additional packages and services that are not required for focused IoT deployments.',
            'business_impact' => 'Unnecessary packages and services create avoidable entry points and maintenance obligations.',
            'recommended_controls' => ['package-minimization', 'service-baseline', 'image-hardening'],
        ],
        [
            'id' => 'password-admin',
            'name' => 'Password-based administrative access',
            'severity' => 'High',
            'category' => 'Identity and access',
            'paper_signal' => 'The paper compares password-based access with public-key authentication during SSH V2 scenarios.',
            'business_impact' => 'Weak or reused passwords increase brute-force, phishing, and credential replay risk.',
            'recommended_controls' => ['key-based-auth', 'password-auth-policy', 'admin-network'],
        ],
        [
            'id' => 'unverified-public-key',
            'name' => 'Unverified public key trust',
            'severity' => 'Medium',
            'category' => 'Trust validation',
            'paper_signal' => 'The paper recommends using a certificate authority or signed public keys to confirm key authenticity.',
            'business_impact' => 'Administrators may trust an attacker-controlled key during onboarding or replacement.',
            'recommended_controls' => ['signed-keys', 'key-inventory', 'change-control'],
        ],
        [
            'id' => 'open-remote-services',
            'name' => 'Unnecessary remote services',
            'severity' => 'Medium',
            'category' => 'Exposure management',
            'paper_signal' => 'The paper discusses remote services and preinstalled tools as potential risk multipliers on board images.',
            'business_impact' => 'Attackers can pivot from exposed management services to broader device compromise.',
            'recommended_controls' => ['service-baseline', 'firewall-policy', 'exposure-review'],
        ],
        [
            'id' => 'post-compromise-privilege-gain',
            'name' => 'Privilege escalation after SSH compromise',
            'severity' => 'High',
            'category' => 'Host hardening',
            'paper_signal' => 'The paper notes that even a non-root compromise can lead to privilege escalation when the host is weakly maintained.',
            'business_impact' => 'A limited account can become a full device takeover when local hardening is incomplete.',
            'recommended_controls' => ['least-privilege', 'host-hardening', 'audit-logging'],
        ],
    ],
    'controls' => [
        [
            'id' => 'ssh-protocol-2',
            'name' => 'Enforce SSH protocol version 2',
            'category' => 'SSH configuration',
            'weight' => 12,
            'maturity' => 'Foundation',
            'implementation' => 'Validate the effective SSH daemon configuration and ensure SSH V1 cannot be negotiated.',
            'evidence' => 'Configuration review, service restart record, and scanner output confirming that only SSH V2 is accepted.',
        ],
        [
            'id' => 'regenerate-host-keys',
            'name' => 'Regenerate board host keys before network use',
            'category' => 'Cryptographic assurance',
            'weight' => 11,
            'maturity' => 'Foundation',
            'implementation' => 'Remove first-boot host keys from cloned images and regenerate keys on the target board after entropy is ready.',
            'evidence' => 'Provisioning record showing host-key removal, regeneration command, fingerprint capture, and approval.',
        ],
        [
            'id' => 'hardware-rng',
            'name' => 'Enable a hardware-backed entropy source',
            'category' => 'Cryptographic assurance',
            'weight' => 10,
            'maturity' => 'Managed',
            'implementation' => 'Load the board-supported random number generator module, enable the entropy service, and verify entropy availability before key generation.',
            'evidence' => 'Boot log, entropy service status, and key generation runbook.',
        ],
        [
            'id' => 'openssh-patching',
            'name' => 'Maintain OpenSSH patch currency',
            'category' => 'Patch management',
            'weight' => 9,
            'maturity' => 'Managed',
            'implementation' => 'Track OpenSSH package versions, vendor advisories, and approved maintenance windows for board images.',
            'evidence' => 'Version inventory, update policy, vulnerability review, and remediation record.',
        ],
        [
            'id' => 'signed-keys',
            'name' => 'Use signed keys or trusted key authority',
            'category' => 'Trust validation',
            'weight' => 8,
            'maturity' => 'Advanced',
            'implementation' => 'Use a trusted authority or signed public keys to validate administrative identities and host trust.',
            'evidence' => 'Key authority policy, signed-key record, host certificate, or trusted fingerprint register.',
        ],
        [
            'id' => 'key-based-auth',
            'name' => 'Prefer key-based administration',
            'category' => 'Identity and access',
            'weight' => 7,
            'maturity' => 'Managed',
            'implementation' => 'Use strong administrative key pairs, protect private keys, and disable password authentication where operationally feasible.',
            'evidence' => 'Authorized key inventory, private-key protection standard, and password-auth exception register.',
        ],
        [
            'id' => 'ssh-config-audit',
            'name' => 'Audit SSH daemon configuration',
            'category' => 'Assurance',
            'weight' => 7,
            'maturity' => 'Foundation',
            'implementation' => 'Review daemon settings for protocol, authentication, ciphers, root login, logging, and idle timeout requirements.',
            'evidence' => 'Audited sshd_config snapshot, reviewer sign-off, and exception notes.',
        ],
        [
            'id' => 'mitm-monitoring',
            'name' => 'Monitor for local man-in-the-middle indicators',
            'category' => 'Network trust',
            'weight' => 7,
            'maturity' => 'Advanced',
            'implementation' => 'Detect ARP anomalies, duplicate addresses, unexpected gateway changes, and new management-path intermediaries.',
            'evidence' => 'Network monitoring rule, sample alert, and incident triage procedure.',
        ],
        [
            'id' => 'network-segmentation',
            'name' => 'Segment development-board management traffic',
            'category' => 'Network trust',
            'weight' => 7,
            'maturity' => 'Managed',
            'implementation' => 'Place board administration on a controlled management segment with restricted peer access.',
            'evidence' => 'Network diagram, access control list, and test connection results.',
        ],
        [
            'id' => 'admin-network',
            'name' => 'Restrict SSH to approved administration sources',
            'category' => 'Exposure management',
            'weight' => 7,
            'maturity' => 'Managed',
            'implementation' => 'Limit SSH access to known administration hosts, bastions, VPNs, or management subnets.',
            'evidence' => 'Firewall policy, allowed source list, and verification scan.',
        ],
        [
            'id' => 'package-minimization',
            'name' => 'Minimize default packages',
            'category' => 'System minimization',
            'weight' => 6,
            'maturity' => 'Managed',
            'implementation' => 'Remove games, desktop utilities, unused interpreters, and packages not required by the target use case.',
            'evidence' => 'Package baseline, removal log, and approved image manifest.',
        ],
        [
            'id' => 'service-baseline',
            'name' => 'Maintain a service exposure baseline',
            'category' => 'Exposure management',
            'weight' => 6,
            'maturity' => 'Foundation',
            'implementation' => 'Define expected open ports and running services for each board role and scan against the baseline.',
            'evidence' => 'Nmap scan result, running-service list, and exception register.',
        ],
        [
            'id' => 'firewall-policy',
            'name' => 'Apply host firewall rules',
            'category' => 'Host hardening',
            'weight' => 6,
            'maturity' => 'Managed',
            'implementation' => 'Deny unsolicited inbound traffic by default and explicitly allow required management flows.',
            'evidence' => 'Host firewall configuration and external scan confirmation.',
        ],
        [
            'id' => 'image-hardening',
            'name' => 'Harden and version board images',
            'category' => 'System minimization',
            'weight' => 6,
            'maturity' => 'Advanced',
            'implementation' => 'Build reusable images with approved packages, key regeneration hooks, logging, and secure defaults.',
            'evidence' => 'Image build file, checksum, release note, and rollback record.',
        ],
        [
            'id' => 'version-baseline',
            'name' => 'Inventory board OS and OpenSSH versions',
            'category' => 'Asset intelligence',
            'weight' => 5,
            'maturity' => 'Foundation',
            'implementation' => 'Capture board model, operating-system image, kernel version, OpenSSH version, and management endpoint.',
            'evidence' => 'Inventory export and change history.',
        ],
        [
            'id' => 'vulnerability-tracking',
            'name' => 'Track vulnerability exposure by version',
            'category' => 'Patch management',
            'weight' => 5,
            'maturity' => 'Managed',
            'implementation' => 'Map detected versions to advisories, CVEs, and remediation status for each board fleet.',
            'evidence' => 'Vulnerability register, risk owner, and closure evidence.',
        ],
        [
            'id' => 'key-inventory',
            'name' => 'Maintain host and administrator key inventory',
            'category' => 'Cryptographic assurance',
            'weight' => 5,
            'maturity' => 'Managed',
            'implementation' => 'Record host fingerprints, administrator keys, rotation dates, revocation status, and authorized devices.',
            'evidence' => 'Key register and periodic reconciliation report.',
        ],
        [
            'id' => 'password-auth-policy',
            'name' => 'Control password-authentication exceptions',
            'category' => 'Identity and access',
            'weight' => 4,
            'maturity' => 'Managed',
            'implementation' => 'Require strong approval, expiry, monitoring, and compensating controls for password-based SSH access.',
            'evidence' => 'Exception ticket, expiry date, and monitoring rule.',
        ],
        [
            'id' => 'least-privilege',
            'name' => 'Apply least privilege for board accounts',
            'category' => 'Host hardening',
            'weight' => 4,
            'maturity' => 'Managed',
            'implementation' => 'Separate operator, developer, and administrator roles; limit sudo; and remove shared accounts.',
            'evidence' => 'Account review, sudoers policy, and access recertification.',
        ],
        [
            'id' => 'host-hardening',
            'name' => 'Apply host-level hardening controls',
            'category' => 'Host hardening',
            'weight' => 4,
            'maturity' => 'Managed',
            'implementation' => 'Disable unused accounts, enforce logging, remove insecure defaults, and validate secure boot-time configuration.',
            'evidence' => 'Hardening checklist, configuration snapshot, and exception register.',
        ],
        [
            'id' => 'audit-logging',
            'name' => 'Centralize administrative audit logging',
            'category' => 'Assurance',
            'weight' => 3,
            'maturity' => 'Advanced',
            'implementation' => 'Forward authentication logs, command audit events, and configuration changes to a protected log destination.',
            'evidence' => 'Log forwarding status, sample event, retention policy, and review record.',
        ],
        [
            'id' => 'change-control',
            'name' => 'Control SSH and image changes',
            'category' => 'Assurance',
            'weight' => 3,
            'maturity' => 'Managed',
            'implementation' => 'Require review and traceability for SSH policy, key authority, image, and firewall changes.',
            'evidence' => 'Approved change record and post-change validation.',
        ],
        [
            'id' => 'exposure-review',
            'name' => 'Review exposed interfaces before deployment',
            'category' => 'Exposure management',
            'weight' => 3,
            'maturity' => 'Foundation',
            'implementation' => 'Run a pre-deployment review for open ports, discovery signals, default credentials, and remote access paths.',
            'evidence' => 'Pre-deployment checklist and scan evidence.',
        ],
    ],
    'scenarios' => [
        [
            'id' => 'legacy-v1-v2',
            'name' => 'Legacy SSH V1 and V2 enabled',
            'risk' => 'Critical',
            'description' => 'The board accepts both protocol generations, creating downgrade exposure during hostile local-network conditions.',
            'recommended_action' => 'Disable SSH V1 immediately and validate the effective daemon configuration through scanning.',
        ],
        [
            'id' => 'v2-password',
            'name' => 'SSH V2 with password administration',
            'risk' => 'High',
            'description' => 'Protocol downgrade is reduced, but credential guessing and password reuse remain material concerns.',
            'recommended_action' => 'Move toward protected key-based administration and restrict source networks.',
        ],
        [
            'id' => 'v2-public-key',
            'name' => 'SSH V2 with public-key administration',
            'risk' => 'Medium',
            'description' => 'Authentication strength improves, but weak first-boot host keys and unverified public-key trust can still undermine assurance.',
            'recommended_action' => 'Regenerate host keys with sufficient entropy and maintain key inventory.',
        ],
        [
            'id' => 'hardened-signed-keys',
            'name' => 'Hardened SSH with regenerated and signed keys',
            'risk' => 'Low',
            'description' => 'The board uses SSH V2, regenerated host keys, trusted public-key validation, controlled exposure, and monitored administration paths.',
            'recommended_action' => 'Maintain patch cadence, continuous evidence, and periodic key review.',
        ],
    ],
];

